### ISSUE TITLE
UnboundLocalError

### ISSUE THREAD

**Issue by dpellegr** [SixTrack/SixDeskDB#23]
I am getting this error with Sixdb. It was working fine earlier in the morning. Could it be the last update?

$ ./sixdb ats2017wire_-25_250.db da
Opened ats2017wire_-25_250.db successfully

Error in `da' command.

Traceback (most recent call last):
  File "./sixdb", line 50, in run
    getattr(self,cmd)(study)
  File "./sixdb", line 105, in da
    SixDeskDB(study).mk_da(force=force,nostd=nostd)
  File "/afs/cern.ch/project/sixtrack/SixDeskDB/sixdeskdb/deskdb.py", line 1876, in mk_da
    self.read10b()
  File "/afs/cern.ch/project/sixtrack/SixDeskDB/sixdeskdb/deskdb.py", line 1837, in read10b
    print fmt%(tunex,tuney,angle,seed,ns1l,ns2l)
UnboundLocalError: local variable 'fmt' referenced before assignment

**Comment by rdemaria** [comment]
Fixed it 10 minutes ago...

**Comment by dpellegr** [comment]
Indeed it looks ok now. Thanks!
