### ISSUE TITLE
Check results failing

### ISSUE THREAD

**Issue by dpellegr** [SixTrack/SixDeskDB#25]
It looks like check_results constantly fails even with DBs that used to be ok.
_____________________________

Opened ats2017wire_075_175.db successfully

Error in `check_results' command.

Traceback (most recent call last):
  File "./sixdb", line 50, in run
    getattr(self,cmd)(study)
  File "./sixdb", line 146, in check_results
    noproblem=SixDeskDB(study).check_results()
  File "/afs/cern.ch/project/sixtrack/SixDeskDB/sixdeskdb/deskdb.py", line 2620, in check_results
    noproblem =self.check_overlap()
  File "/afs/cern.ch/project/sixtrack/SixDeskDB/sixdeskdb/deskdb.py", line 2604, in check_overlap
    amps2=sorted(set(sum([amp.split(':') for amp in amps],[])))
UnboundLocalError: local variable 'amps' referenced before assignment

**Comment by rdemaria** [comment]
It was a bug, it should be fixed now

**Comment by dpellegr** [comment]
I confirm that it is fixed
